version: "3.8"

services:
  fluentd:
    image: fluentd-prom:21e577e       # <- thay cho build:
    command: ["fluentd", "-c", "/fluentd/etc/fluentd.conf", "-vv"]

    # (khuyên dùng khi tail /var/log host)
    user: "0:0"

    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf:ro
      - /var/log:/var/log:ro
    ports:
      - "24231:24231"    # /metrics cho Prometheus
      - "24220:24220"    # (tuỳ chọn) monitor_agent

    # (khuyên dùng) healthcheck để Swarm biết container còn sống
#    healthcheck:
#      test: ["CMD-SHELL", "wget -qO- http://localhost:24231/metrics >/dev/null 2>&1 || exit 1"]
#      interval: 30s
#      timeout: 5s
#      retries: 5
#      start_period: 20s

    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "prometheus.enable=true"
        - "prometheus.port=24231"
        - "prometheus.path=/metrics"
        - "prometheus.job=fluentd"
    networks:
      - observability

  prometheus:
    image: prom/prometheus:v2.55.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # Nếu bạn muốn dùng Docker Swarm Service Discovery, mount docker.sock:
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9090:9090"
    networks:
      - observability

  grafana:
    image: grafana/grafana:10.4.3
    ports:
      - "3000:3000"
    networks:
      - observability

networks:
  observability:
    driver: overlay
